// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umugzdepvpezfmnjowcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdWd6ZGVwdnBlemZtbmpvd2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NjQ0MTMsImV4cCI6MjA1MDU0MDQxM30.FXnYncuemGGdMtwRDG7UffUozrN3jocuu7LFYMsnn38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);